### PR TITLE
Accept E1000E network devices

### PR DESCRIPTION
**Pull request by rudnerbjoern**
According to vmware there is a network device type named E1000E (see: https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.html.hostclient.doc/GUID-AF9E24A8-2CFA-447B-AC83-35D563119667.html)

The device is of class "VirtualE1000e"

### CODE REVIEW

**Review by Hipska — APPROVED** [review]

**Comment by Molkobain** [comment]
Hello @rudnerbjoern ,

Thanks for the PR! It will be discussed during next PR review early june, but the change seems pretty straight forward so it should not be a problem.
Do you have this device in your environment yourself?

_Note: Ask integration team if they encountered it._

**Review by Molkobain — APPROVED** [review]

**Comment by rudnerbjoern** [comment]
> Hello @rudnerbjoern ,
> 
> 
> Do you have this device in your environment yourself?
> 
Yes, I have several of these. As no NIC was added to these VMs I debugged the response and found that E1000e device.

**Comment by Molkobain** [comment]
Great thanks, it will be discussed during next PR review (early June)

**Comment by piRGoif** [comment]
Discussed during technical review : OK, will be reviewed next week in functional review

**Comment by piRGoif** [comment]
Functional review OK !
Merging... This will we included in future collector version

**Comment by piRGoif** [comment]
Hello @rudnerbjoern, many thanks for your contribution !
As a thank you gift we are sending some stickers to our contributors (see https://github.com/Combodo/iTop/blob/develop/CONTRIBUTING.md#-we-are-thankful)
Can you send me your real name and postal address ? => pierre.goiffon  =at=  combodo.com (replace "  =at=  " with "@")

**Pull request merged**
